# uses xcodebuild and xcpretty to test Swift snapshots
# on local Mac use the following command to set xcodebuild to use Xcode Beta
# sudo xcode-select -s /Applications/Xcode-Beta.app/Contents/Developer
#os:
#- osx
#sudo: required
#xcode_project: SwiftyBeaver.xcodeproj
#xcode_scheme: SwiftyBeaver (iOS)
#osx_image: xcode8
#xcode_sdk: iphonesimulator10.0
#before_install:
#- gem install xcpretty
#script:
#- set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
#- xcodebuild test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -project SwiftyBeaver.xcodeproj -scheme "SwiftyBeaver (iOS)" -destination name="iPhone 6" | xcpretty -c

language: objective-c
osx_image: xcode8
xcode_project: SwiftyBeaver.xcodeproj
xcode_scheme: SwiftyBeaver (iOS)
xcode_sdk: iphonesimulator8.4
install: true
dist: osx
os: osx
